# This is the configuration for the node.
# Use ENV_NAME to replace the values with environment variables for private keys.
# OWNER_PRIVATE_KEY is optional
keys:
  ownerPrivateKey: OWNER_PRIVATE_KEY
  workerPrivateKey: WORKER_PRIVATE_KEY

local:
  cacheDir: ./.cache

network:
  rpcUrl: https://rpc.dtn.network
  chainId: 1337
  nodeManagerAddress: 0x1234567890123456789012345678901234567890
  modelManagerAddress: 0x1234567890123456789012345678901234567890
  namespaceManagerAddress: 0x1234567890123456789012345678901234567890

model-apis:
  - name: "api.node.alice.my-custom-api-text"
    specs: "string[] -> string"
    docs: |
      prompt: provide prompt (multiple string will be joined)
  - name: "api.node.alice.my-custom-api-image"
    specs: "string[], uint8, uint64, uint64 -> bytes"
    docs: |
      prompt: provide prompt (multiple string will be joined)
      response-type: 0 for old model, 1 for new model
      dimension-x: width of the image
      dimension-y: height of the image

custom-models:
  - name: "model.node.alice.my-custom-model"
    api: "api.node.alice.my-custom-api"

node:
  username: alice
  nodeName: node1
  worker: 0x1234567890123456789012345678901234567890
  models:
    - name: model.system.openai-gpt-4
      priceMinPerByteIn: 1000
      priceMaxPerByteOut: 10000
      host: "http://localproxy:8080/"
    - name: model.node.alice.my-custom-model
      priceMinPerByteIn: 1000
      priceMaxPerByteOut: 10000
      host: "http://gpuhost:8080/"
  trustNamespaces:
    - "system.trust.dtn"
